"""empty message

Revision ID: 12225083236d
Revises: 2d7d965b9766
Create Date: 2014-12-03 19:09:24.168690

"""

# revision identifiers, used by Alembic.
revision = '12225083236d'
down_revision = '2d7d965b9766'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('title')

    ### end Alembic commands ###
