"""empty message

Revision ID: 12e737414f44
Revises: 13ec90e05246
Create Date: 2015-01-18 19:25:40.325092

"""

# revision identifiers, used by Alembic.
revision = '12e737414f44'
down_revision = '13ec90e05246'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
