"""empty message

Revision ID: 13ec90e05246
Revises: 24be3a15254c
Create Date: 2015-01-18 19:15:34.158940

"""

# revision identifiers, used by Alembic.
revision = '13ec90e05246'
down_revision = '24be3a15254c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_login_ip', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('current_login_ip')
        batch_op.drop_column('current_login_at')

    ### end Alembic commands ###
