"""empty message

Revision ID: 15124e6e084f
Revises: 12225083236d
Create Date: 2015-01-04 21:25:55.397207

"""

# revision identifiers, used by Alembic.
revision = '15124e6e084f'
down_revision = '12225083236d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
