"""empty message

Revision ID: 24be3a15254c
Revises: 50e2f921d0a1
Create Date: 2015-01-08 22:40:53.472166

"""

# revision identifiers, used by Alembic.
revision = '24be3a15254c'
down_revision = '50e2f921d0a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    ### end Alembic commands ###
