"""empty message

Revision ID: 3b2fb7373c28
Revises: 15124e6e084f
Create Date: 2015-01-06 22:16:32.515513

"""

# revision identifiers, used by Alembic.
revision = '3b2fb7373c28'
down_revision = '15124e6e084f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
