"""empty message

Revision ID: 43f47b570e4d
Revises: 3b2fb7373c28
Create Date: 2015-01-06 22:19:36.418352

"""

# revision identifiers, used by Alembic.
revision = '43f47b570e4d'
down_revision = '3b2fb7373c28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    ### end Alembic commands ###
