"""empty message

Revision ID: 50e2f921d0a1
Revises: 43f47b570e4d
Create Date: 2015-01-08 21:51:54.154827

"""

# revision identifiers, used by Alembic.
revision = '50e2f921d0a1'
down_revision = '43f47b570e4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    ### end Alembic commands ###
