"""empty message

Revision ID: 533a13397f97
Revises: 12e737414f44
Create Date: 2015-01-18 19:26:06.870032

"""

# revision identifiers, used by Alembic.
revision = '533a13397f97'
down_revision = '12e737414f44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
